In [255]:
# Importando Paquetes
import requests
import os,json
import pandas as pd
import plotly.plotly as py
import cufflinks as cf
import numpy as np
from sklearn.neighbors.kde import KernelDensity
import scipy.stats as st
import plotly.plotly as py
from plotly import tools
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
from scipy.stats import norm
import numpy as np
import warnings
pd.set_option('precision',2)

In [419]:
var_to_analyze='resultado'

In [420]:
def reader_json(path_json):
    path_to_json=(r'C:\Users\luism\OneDrive\Escritorio\data')
    json_files = [pos_json for pos_json in os.listdir(path_to_json) if pos_json.endswith('.json')]
    num = (len(json_files))
    diccionario = []
    for i in range(num-1):
        json_filesx=pd.read_json(r'C:\Users\luism\OneDrive\Escritorio\data'+'/'+json_files[i+0])
        diccionario.append(json_filesx)
    diccionario=pd.concat(diccionario,axis=1)
    return(diccionario)
reader_json(r'C:\Users\luism\OneDrive\Escritorio\data')

,resultado_0,resultado_1,resultado_2,resultado_3,resultado_4,resultado_5,resultado_6
datos,{'clientes': {'inactive': {'periodo': [{'adq':...,{'clientes': {'inactive': {'periodo': [{'adq':...,{'clientes': {'inactive': {'periodo': [{'adq':...,{'clientes': {'inactive': {'periodo': [{'adq':...,{'clientes': {'inactive': {'periodo': [{'adq':...,{'clientes': {'inactive': {'periodo': [{'adq':...,{'clientes': {'inactive': {'periodo': [{'adq':...
parametros,{'ppc': 50000},{'ppc': 50000},{'ppc': 50000},{'ppc': 50000},{'ppc': 50000},{'ppc': 50000},{'ppc': 50000}
valuacion,1.4e+07,1.2e+07,1.3e+07,2e+07,1.4e+07,1.6e+07,1.3e+07

In [421]:
dicci=dict()
for icount in range(len(diccionario.columns)):
    tempkey='resultado_'+str(icount)
    dicci[icount+1]=diccionario[tempkey]['datos']['flujos'][var_to_analyze]
    dicci=pd.Series(dicci)

In [422]:
a=pd.DataFrame(dicci[1]).transpose()
b=pd.DataFrame(dicci[2]).transpose()
c=pd.DataFrame(dicci[3]).transpose()
d=pd.DataFrame(dicci[4]).transpose()
e=pd.DataFrame(dicci[5]).transpose()
f=pd.DataFrame(dicci[6]).transpose()
g=pd.DataFrame(dicci[7]).transpose()
data=pd.concat([a,b,c,d,e,f,g],axis=0)
a=data.max(axis=0) 
b=data.min(axis=0)
a= pd.DataFrame([[key, a[key]] for key in a.keys()], columns=['meses','valores'])
b= pd.DataFrame([[key, b[key]] for key in b.keys()], columns=['meses','valores'])
a.describe()

       meses   valores
count  96.00  9.60e+01
mean   47.50  8.24e+05
std    27.86  1.87e+05
min     0.00  1.40e+05
25%    23.75  6.87e+05
50%    47.50  8.19e+05
75%    71.25  9.75e+05
max    95.00  1.18e+06

In [423]:
b.describe()

       meses    valores
count  96.00      96.00
mean   47.50  318539.78
std    27.86   85633.27
min     0.00  -34314.07
25%    23.75  269825.34
50%    47.50  332012.68
75%    71.25  360112.86
max    95.00  481813.70

In [424]:
def timeseries(diccionario,var_to_analyze):
    serie_0 = go.Scatter(
                x=a['meses'],
                y=a['valores'],
                name = "Serie limite superior",
                line = dict(color = '#17BECF'),
                opacity = 0.8)

    serie_1 = go.Scatter(
                x=b['meses'],
                y=b['valores'],
                name = "Serie limite inferior",
                line = dict(color = '#7F7F7F'),
                opacity = 0.8)

    data = [serie_0,serie_1]

    layout = dict(
    title = ('Series de tiempo '+ var_to_analyze),
    xaxis=dict(range = [0,96],title='Periodo(meses)'),
    yaxis=dict(title='Cantidad(pesos)')
    )
    
    fig = dict(data=data, layout=layout)
    #data1 = pd.Series(serie_superior)
    #describemax = pd.DataFrame(data=data1.describe())
    #describemax.rename(columns={0:'Estadística serie superior'},inplace=True)
    #data2 = pd.Series(serie_inferior)
    #describemin = pd.DataFrame(data=data2.describe())
    #describemin.rename(columns={0:'Estadística serie inferior'},inplace=True)
    #print(describemin)
    #print(describemax)
    return(iplot(fig, filename = "Series de tiempo"))
timeseries(data,var_to_analyze)